# Generated by Django 3.1.7 on 2021-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='teacher_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
