# Generated by Django 3.1.7 on 2021-06-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att_man', '0002_lecture_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
    ]
